version: "3.7"

services:
  app:
    build: "./app"
    container_name: app
    restart: always
    ports:
      - 80:80
    volumes:
      - ./app/:/var/www/html
    depends_on:
      - db
    links:
      - db 
      
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: alfa
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db