version: "3.7"

services:
  app:
    build: "./server"
    container_name: Server
    ports:
      - 80:80
    volumes:
      - ${PWD}/server/:/var/www/html/
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: alfa
      POSTGRES_USER: jedi
      POSTGRES_DB: technews
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql:z
      - ${PWD}/db/scripts:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
volumes:
  pgdata:      