version: "3.7"

services:
  nginx:
    image: nginx:1.17.8
    container_name: server
    ports:
      - 80:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./server:/var/www
    links:
      - app
  app:
    build: "./server"
    container_name: app
    ports:
      - 9000:9000
    volumes:
      - ${PWD}/server/:/var/www
    depends_on:
      - db
    links:
      - db
      - server

  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: alfa
      POSTGRES_USER: jedi
      POSTGRES_DB: technews
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql:z
      - ${PWD}/config/db:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db

volumes:
  pgdata:      