CREATE TABLE IF NOT EXISTS news (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  date TIMESTAMP
);

INSERT INTO news (title, date, content) VALUES ('NewsController', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 2', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 3', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 4', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 5', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 6', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 7', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 8', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 9', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 10', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 11', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 12', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 13', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 14', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 15', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 16', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 17', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 18', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 19', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

INSERT INTO news (title, date, content) VALUES ('NewsController 20', '2022-01-05 03:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ac nisl posuere pharetra. Etiam elementum lectus ac accumsan pretium. Quisque felis purus, venenatis non mauris ac, hendrerit lobortis sem. Nam turpis lacus, rhoncus quis mi semper, faucibus molestie neque. Aliquam molestie lectus ac nibh imperdiet, vitae facilisis eros imperdiet. Morbi neque nisl, placerat fermentum laoreet semper, porta in dui. In ut quam quam. Donec tincidunt pellentesque massa. Vivamus pharetra id quam ut semper. Nam tristique dictum arcu, eu aliquet mauris tempor vitae. Etiam iaculis libero id egestas bibendum. Quisque commodo quis lorem eu lobortis. Suspendisse potenti. Sed vel dignissim arcu.');

